### ISSUE TITLE
Need help for FloweryTTs

### ISSUE THREAD

**Issue by Tomato6966** [topi314/LavaSrc#102]
![image](https://github.com/topi314/LavaSrc/assets/68145571/c0606a5a-bfaa-482b-b552-1ad426dd1928)

For some reason it's not working, but if i do a manual reqeuest via fetch for: 
```
https://api.flowery.pw/v1/tts?voice=Olivia&audio_format=ogg_opus&translate=False&silence=0&speed=1.0&text=Hello%20World
```
it works

my configuration is:

```json
      flowery.tts:
            voice: "Olivia"
            translate: false
            silence: 0
            speed: 1.0
            audioFormat: "mp3"
```

What am I doing wrong?

Lavalink request
```
/v4/loadtracks?identifier=ftts://Hello%20World
```

even with all options it doesn't work

```
/v4/loadtracks?identifier=ftts://Hello%20World?voice=Olivia&audio_format=ogg_opus&translate=False&silence=0&speed=1.0
```

Help is appreciated.

**Comment by topi314** [comment]
there is no release with flowery.tts yet

**Comment by Tomato6966** [comment]
oh, I'm sorry then. but would it be right to do it like that?

**Comment by topi314** [comment]
just use a snapshot from master & see
