### ISSUE TITLE
Flowery TTS not loading track

### ISSUE THREAD

**Issue by lorenblue** [topi314/LavaSrc#104]
Hi,

I anticipate I'm doing something noobish, but why does GET http://localhost:2333/v4/loadtracks?identifier=ftts://hello return nothing?

_Relevant information:_

GET http://localhost:2333/v4/loadtracks?identifier=https://www.youtube.com/watch?v=HsLvnFQW_yM%26t=0 correctly returns a track

flowery.tts:
      voice: "Abeo" # (case-sensitive) get default voice from here https://api.flowery.pw/v1/tts/voices
      translate: false # whether to translate the text to the native language of voice
      silence: 0 # the silence parameter is in milliseconds. Range is 0 to 10000. The default is 0.
      speed: 1.0 # the speed parameter is a float between 0.5 and 10. The default is 1.0. (0.5 is half speed, 2.0 is double speed, etc.)
      audioFormat: "mp3" # supported formats are: mp3, ogg_opus, ogg_vorbis, aac, wav, and flac. Default format is mp3

GET https://api.flowery.pw/v1/tts?voice=Abeo&text=hello returns the correct audio

3.2.6 LavaSrc plugin is correctly found and loaded according to logs

GET http://localhost:2333/v4/loadtracks?identifier=https://open.spotify.com/track/03ZyPqIZXdBNNVIpM2KORq?si=4ba4a81496914701 correctly returns a track

**Comment by lorenblue** [comment]
Oh shoot, I just saw that it is because 3.2.6 doesn't support the TTS yet, my bad. Could you provide an example of how to get the right version please? Right now I have

    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:3.2.6"
       repository: "https://jitpack.io"

**Comment by lorenblue** [comment]
- dependency: "com.github.topi314.lavasrc:lavasrc-plugin:e978577"
      repository: "https://maven.topi.wtf/snapshots"

Still getting null loading the track

**Comment by bachtran02** [comment]
I wasn't able to reproduce your error but it could be that you forgot to set `flowerytts:true` for `plugins.lavasrc.sources` in your `application.yml`

```
plugins:
   lavasrc:
     sources:
         flowerytts: true
```

**Comment by lorenblue** [comment]
Ah okay. Apologies if I misread something or wasn't aware of a certain naming convention, but to me, the fact that it's "flowerytts" and not "flowery.tts" as in the example application.yml @ plugins->lavasrc->sources->flowery.tts) is _highly_ confusing. Also, the "flowerytts: true" is not included in the example application.yml in the first place I believe. Thanks for the help though, works now!

**Comment by topi314** [comment]
i've gone ahead and replaced all uses of `flowery.tts` with `flowerytts`. That should make things easier

https://github.com/topi314/LavaSrc/commit/297508337dbd67f09bc8f214595fbda5cf3655d3

**Comment by topi314** [comment]
this will be in the final release soonish then
