### ISSUE TITLE
4.0.0-beta.7 build failure on JitPack

### ISSUE THREAD

**Issue by freyacodes** [topi314/LavaSrc#125]
See https://jitpack.io/com/github/TopiSenpai/LavaSrc/4.0.0-beta.7/build.log

I think JitPack is unsure of what tasks to run

**Comment by topi314** [comment]
Eh, why are you using jitpack? I host jars on my own repo since that's more reliable

**Comment by freyacodes** [comment]
Because you link to it, and because I looked up the old TopiSenpai group ID when I looked at your repo

**Comment by topi314** [comment]
Where do I link to it?

**Comment by freyacodes** [comment]
First line of the readme
