### ISSUE TITLE
Spotify data missing

### ISSUE THREAD

**Issue by rxnk** [topi314/LavaSrc#132]
When requesting a Spotify track URL with LavaSrc, the album & artwork is always missing even though  Spotify's `/tracks/ID` endpoint does include the album & artwork for the album as seen below:
![image](https://github.com/topi314/LavaSrc/assets/95060559/c8882db9-4260-409c-8887-e59757862bd7)

**Comment by topi314** [comment]
what version are you running?
did you try it with different tracks?

**Comment by topi314** [comment]
Just to be sure, where are you expecting the artwork URL & album?
Because v3 does not support album

**Comment by topi314** [comment]
I mean, you're using LavaSrc v3 with Lavalink v4

That ain't gonna work, I'm honestly surprised it even works

Use LavaSrc v4
