### ISSUE TITLE
Getting Error with Apple Music 

### ISSUE THREAD

**Issue by munishkhatri720** [topi314/LavaSrc#133]
I encountered this error while attempting to retrieve search results using the following query: amsearch: heeriye. I'm using the latest Lavalink v4 beta along with the latest Lavasrc snapshot, and I also have Apple Music's mediaToken.

However, when I use direct links, such as https://music.apple.com/us/album/heeriye-lofi-mix/1654991052?i=1654991054, it works perfectly. Here's the error log for reference: https://pastebin.mozilla.org/sHhhmy2Y.

Application.yml : https://pastebin.mozilla.org/s69Gxynr

**Comment by topi314** [comment]
I think the issue is that the artist id is null.
can you test https://github.com/topi314/LavaSrc/pull/136?

**Comment by munishkhatri720** [comment]
✅ Issue Solved !
