### ISSUE TITLE
Add recommendations from Yandex Music

### ISSUE THREAD

**Issue by Shandeika** [topi314/LavaSrc#147]
Yandex Music can also, like YouTube, offer recommended tracks after completing the main playlist. They call it "Моя волна (по треку | по плейлисту)"
I think it would be useful

**Comment by topi314** [comment]
resolved in https://github.com/topi314/LavaSrc/pull/197

**Comment by topi314** [comment]
published in https://github.com/topi314/LavaSrc/releases/tag/4.1.1
