### ISSUE TITLE
some playlists don't work

### ISSUE THREAD

**Issue by llimonix** [topi314/LavaSrc#152]
there are playlists that provide shortened track information in the Yandex Music API. I have processed this in my script. In your case, he just doesn't see the tracks.

Playlist: https://music.yandex.ru/users/Comicona/playlists/1023

I did this. Made a request with MarshalX YandexMusic API: https://github.com/MarshalX/yandex-music-api

Copied all the id:album_id from the response to client.user_playlist("kind="1023", user_id="Comicona")

And sent a list consisting of a set of data

id:album_id 

On request, client.tracks(list_track)

I received these tracks with full information. I tried it on a playlist with 500+ tracks, everything comes correctly

**Comment by topi314** [comment]
@AgutinVBoy can you look into this?

**Comment by AgutinVBoy** [comment]
Wow. The API response for this playlist is different. For a normal playlist, a json is returned with the content: `"result.tracks[].track.{title, id, artists etc}"`. 
I haven't seen the format for the provided playlist before. Api returns: `"result.tracks[].{id, albumId}"`.  

We need to modify the code: fetch information about each track when such format is found.
I didn't find any other differences in the API response.

**Comment by AgutinVBoy** [comment]
@llimonix, how did you create a playlist like [this](https://music.yandex.ru/users/Comicona/playlists/1023)? 

The only option I can offer now is to create several playlists of different types and deeply analyze the API response to these playlists.

**Comment by llimonix** [comment]
> @llimonix, how did you create a playlist like [this](https://music.yandex.ru/users/Comicona/playlists/1023)?
> 
> The only option I can offer now is to create several playlists of different types and deeply analyze the API response to these playlists.

I took a regular request for a playlist where kind is passed and user_id got an abbreviated view of the tracks: 

![image](https://github.com/topi314/LavaSrc/assets/58168234/b1440662-d020-4fba-b252-4985d7424bb8)


Then I took and made a request with a combination of all track_id:album_id per request: https://api.music.yandex.net/tracks?trackIds=82876164%2C86356254%2C80782933%2C83291070%2C86726809%2C84019953%2C87706317%2C66781909%2C85740709%2C85815221 - where %2C is a comma

And I got the full view of the tracks.

![image](https://github.com/topi314/LavaSrc/assets/58168234/197124f5-a2f6-4ba0-97f6-5ccaf01c7335)


Tested on 500+ tracks in the album, it accepts apparently any long list

**Comment by AgutinVBoy** [comment]
The maximum length of the request (or rather arguments separated by comma) is 6560 characters (I found out experimentally. After that I get error 431). The average track id length is 10 characters (including comma).  
I think for safety we can make several requests, separating 300-500 tracks each.

**Comment by llimonix** [comment]
> The maximum length of the request (or rather arguments separated by comma) is 6560 characters (I found out experimentally. After that I get error 431). The average track id length is 10 characters (including comma). I think for safety we can make several requests, separating 300-500 tracks each.

я делал 500+ у меня все сработало

**Comment by llimonix** [comment]
When should I wait for the update?

**Comment by topi314** [comment]
This issue is up for someone to grab and fix.

I personally don't use Yandex and therefore don't really have interest to look into when I'm busy with other stuff.

**Comment by llimonix** [comment]
> This issue is up for someone to grab and fix.
> 
> I personally don't use Yandex and therefore don't really have interest to look into when I'm busy with other stuff.

can I recompile the plugin with a fix myself, or can I send you an updated file for Yandex and you compile it yourself?

**Comment by topi314** [comment]
you can open pr with these changes sure

**Comment by llimonix** [comment]
https://mega.nz/folder/fy4CgKRT#VuXGCKVatNGTAZ8581pgjw

I made a parse of bad playlists in my own way

First, he tries to get the tracks in the usual way, if nothing is included in the list, he parses through another link described above.

A pack of 300 tracks each. If there are not 300 tracks, then he immediately makes a request for all the IDs

I also set the limit of songs on the artist's link to 300, previously there were 10. It is not clear why. If the artist has less than 300 tracks, he will also parse everything correctly

**Comment by topi314** [comment]
I'm not gonna download a zip from mega, if you want this fixed open a pull request instead
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by llimonix** [comment]
I'm not good at github and what to do here. So it's your right to use or not. The main thing is that everything works for me, and the rest is not important

**Comment by topi314** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by llimonix** [comment]
I made a fork of the project, you can see all the changes

**Comment by llimonix** [comment]
although now I understand that that If else if check could have been done without checking for the number of tracks. He would have divided the chunks normally if there were less than the specified number.

**Comment by topi314** [comment]
> I made a fork of the project, you can see all the changes

then next open a pull request

**Comment by llimonix** [comment]
> > I made a fork of the project, you can see all the changes
> 
> then next open a pull request

check

**Comment by topi314** [comment]
I'll take a look later & leave feedback in the pull request

**Comment by llimonix** [comment]
I will add another text search fix in 2024. Instead of searching only for a track, the most appropriate option will be selected, whether it is a track, playlist or album. I rewrote the logic a bit and slightly fixed erroneous attempts to process json when it did not exist

**Comment by Krispeckt** [comment]
Is it still relevant?

**Comment by topi314** [comment]
There was some sort of misunderstanding on what exactly they wanted
Check the linked pr above

**Comment by llimonix** [comment]
No, it's no longer relevant. It was fixed in some of the updates
Please pay attention to a minor flaw
https://github.com/topi314/LavaSrc/issues/164

**Comment by Krispeckt** [comment]
> No, it's no longer relevant. It was fixed in some of the updates
> 
> Please pay attention to a minor flaw
> 
> 
> 

Meaning with the plugin fix or yandex music api?

**Comment by llimonix** [comment]
> plugin

plugin

**Comment by llimonix** [comment]
> > No, it's no longer relevant. It was fixed in some of the updates
> > Please pay attention to a minor flaw
> 
> Meaning with the plugin fix or yandex music api?

plugin

**Comment by Krispeckt** [comment]
![image](https://github.com/topi314/LavaSrc/assets/105949686/ee644627-700f-4727-ae3e-91da3e8c9ac5)
![image](https://github.com/topi314/LavaSrc/assets/105949686/1f9b8b5e-d82b-4a0e-80fe-a864b9e04ebb)

Xd, and you should have just read the documentation and not made anything up

**Comment by topi314** [comment]
not sure what this is supposed to mean

**Comment by topi314** [comment]
since this seems to be resolved I am gonna close this issue
