### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by Tomato6966** [topi314/LavaSrc#156]
Hello topi, First thanks for that library, I used it long time now and usually serves me well especially with spotify and deezer as a search-source!

I'm here with some issues you might want to know about!

# Apple Music

Seems like the filters are returning mixed up results or am i tripping?
```
/v4/loadsearch?query=amsearch:abba&types=artist
{
  tracks: [],
  albums: [],
  artists: [],
  playlists: [ { info: [Object], pluginInfo: [Object], tracks: [] } ],
  texts: [],
  pluginInfo: {}
}

/v4/loadsearch?query=amsearch:abba&types=album
{
  tracks: [],
  albums: [],
  artists: [ { info: [Object], pluginInfo: [Object], tracks: [] } ],
  playlists: [],
  texts: [],
  pluginInfo: {}
}

/v4/loadsearch?query=amsearch:abba&types=playlist
{
  tracks: [],
  albums: [ { info: [Object], pluginInfo: [Object], tracks: [] } ],
  artists: [],
  playlists: [],
  texts: [],
  pluginInfo: {}
}
```
Tho when I use a source like: deezer / spotify it's correctly filtered.

# For youtube:
Loading something from ytsearch / ytmsearch usually does not work for all filters
only tracks and artists, tho i wouldn't know why you couldn't return playlists?
- maybe state that in the readme. or should i use something else than ytsearch and ytmsearch?

/v4/loadsearch?query=ytsearch:abba&types=playlist,track,album,artist returns just a result in text
/v4/loadsearch?query=ytmsearch:abba&types=playlist,track,album,artist returns just artists and playlists (i tested over 20 queries and never got other results)

**Comment by topi314** [comment]
apple music fixed in https://github.com/topi314/LavaSrc/commit/b3e5bec19078f1586e2ac954782d31e5181f4bab
as for yt, that's simply a limitation of the yt api we use

**Comment by Tomato6966** [comment]
Ah I see, then maybe you wanna state what ytsearch / ytmsearch is capable to return (suggestion)
Thx for the fix!
