### ISSUE TITLE
Yandex music.kz / music.by

### ISSUE THREAD

**Issue by llimonix** [topi314/LavaSrc#164]
ru and com addresses are present in the processing of tracks. But there can also be kz and by

![image](https://github.com/topi314/LavaSrc/assets/58168234/1506cd38-ab92-49db-b6b6-469962661c71)

https://music.yandex.by/users/llimonix123/playlists/3
https://music.yandex.kz/users/llimonix123/playlists/3

You need to change the regular expression and add kz and by there

**Comment by topi314** [comment]
resolved in https://github.com/topi314/LavaSrc/pull/197

**Comment by topi314** [comment]
published in https://github.com/topi314/LavaSrc/releases/tag/4.1.1
