### ISSUE TITLE
Spotify Playlist with Podcasts

### ISSUE THREAD

**Issue by emirkabal** [topi314/LavaSrc#186]
When there are podcasts in the playlist, the request goes into timeout, podcasts can be ignored for a solution.

**Comment by topi314** [comment]
do you have an example playlist for me?

**Comment by topi314** [comment]
fixed in https://github.com/topi314/LavaSrc/commit/d35f8934fe66b8a453dba1d09d6a1374e9ce8fed & https://github.com/topi314/LavaSrc/commit/70f14d2c776663114ee3d614cc0294d738025f84

this will be included in the next release but you can run the snapshot version for now

**Comment by topi314** [comment]
published in https://github.com/topi314/LavaSrc/releases/tag/4.1.1
