### ISSUE TITLE
Mp3 frame not found from yandex music track

### ISSUE THREAD

**Issue by Krispeckt** [topi314/LavaSrc#193]
Checked on different tokens, sometimes it throws the error Mp3 frame not found. In addition, I checked on other sources everything works correctly. The error is not tied to a specific track

Lavalink log
[lavalink.log](https://github.com/topi314/LavaSrc/files/15286631/lavalink.log)

**Comment by llimonix** [comment]
I noticed that the tracks work in the application and so on, if they were saved, but when clicking on the track link, Yandex gives an error

**Comment by llimonix** [comment]
> I noticed that the tracks work in the application and so on, if they were saved, but when clicking on the track link, Yandex gives an error

I think the problem is still on the Yandex Music side.

**Comment by Krispeckt** [comment]
> I noticed that the tracks work in the application and so on, if they were saved, but when clicking on the track link, Yandex gives an error
> 
> 
> 
> I think the problem is still on the Yandex Music side.

I don't know, but if you follow the link to the mp3 track is there and it plays. I started noticing the error a week ago, but rarely. I'm also inclined to the option that this problem will probably resolve itself in time.

**Comment by Krispeckt** [comment]
Now checked yandex music from lavaplayer and it works correctly compared to the plugin. So, there is a suggestion to just take it and implement it in the plugin :>

**Comment by llimonix** [comment]
> Now checked yandex music from lavaplayer and it works correctly compared to the plugin. So, there is a suggestion to just take it and implement it in the plugin :>

I would like at least a temporary fix. Since after a couple dozen errors, the bot goes silent

**Comment by Krispeckt** [comment]
> > Now checked yandex music from lavaplayer and it works correctly compared to the plugin. So, there is a suggestion to just take it and implement it in the plugin :>
> 
> 
> 
> I would like at least a temporary fix. Since after a couple dozen errors, the bot goes silent

I don't know, but I implemented Yandex music in my plugin and I do what I want with it)) At the moment I am satisfied with the work of Yandex music from lavaplayer, but I had to mess with it

**Comment by topi314** [comment]
from what I can tell comparing both there should be no difference in this tho

**Comment by Krispeckt** [comment]
> from what I can tell comparing both there should be no difference in this tho

I also compared, but for some reason Yandex music from lavaplayer works correctly, but from LavaSrc throws errors Mp3 frame not found :/

**Comment by topi314** [comment]
feel free to keep testing, but I would expect both to fail at some point

**Comment by Krispeckt** [comment]
lul, I fixed it :0

**Comment by Krispeckt** [comment]
![image](https://github.com/topi314/LavaSrc/assets/105949686/737db1d5-98c1-463a-aa66-2e665bc13faa)

Really why doesn't it work :/

**Comment by Krispeckt** [comment]
This problem solved?

https://github.com/topi314/LavaSrc/pull/196

**Comment by Krispeckt** [comment]
Problem solved, tested for about 2 hours, not a single error when starting track playback. 

Pr with fix #196

**Comment by topi314** [comment]
this will be included in the next release

**Comment by topi314** [comment]
published in https://github.com/topi314/LavaSrc/releases/tag/4.1.1
