### ISSUE TITLE
Region

### ISSUE THREAD

**Issue by ErrorDoc404** [topi314/LavaSrc#208]
After using lavaSrc in lavalink 4.0.7 region not setting to India

spotify:
    countryCode: "IN"
    
 it featching songs from Spotify US region not IN

**Comment by topi314** [comment]
Can you show your lavalink logs?

**Comment by ErrorDoc404** [comment]
like this?

![image](https://github.com/user-attachments/assets/b36b7918-09a0-4110-8b3f-8aeeb1a8b204)

**Comment by topi314** [comment]
eh I'd also need the responses by lavalink
on that note you shouldnt include `/play` in your search

**Comment by ErrorDoc404** [comment]
the output is very long so I have giving you Pastebin URL hope that helps [link](https://pastebin.com/QKU2hxaN)

**Comment by topi314** [comment]
ok and how are they not in India region?

**Comment by topi314** [comment]
I should prob mention `countryCode` is only used for artist top tracks atm (https://github.com/topi314/LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java#L453)

**Comment by ErrorDoc404** [comment]
means spsearch: <track_name> dont work with countryCode?

**Comment by topi314** [comment]
that is correct
