### ISSUE TITLE
Не загружается плейлист яндекс музыки (kz)

### ISSUE THREAD

**Issue by anDWIN12** [topi314/LavaSrc#224]
https://music.yandex.kz/users/Dmitriyqazaq/playlists/3: ![image](https://github.com/user-attachments/assets/04cf9016-7e0e-47e7-a3b2-8d4e9a1ed90c)

https://music.yandex.ru/users/Dmitriyqazaq/playlists/3: ![image](https://github.com/user-attachments/assets/55537367-1200-41b6-8bb3-b12200b5605f)
версия v2.0.2 mc 1.21

**Comment by topi314** [comment]
this issue tracker is english only
