### ISSUE TITLE
Error when launching LavaSrc plugin.

### ISSUE THREAD

**Issue by stevenalegria9** [topi314/LavaSrc#231]
Hello!

I'm trying to create a server to play music with a discord bot. I'm using this little project to learn java and programming in general as I don't have any experience or knowledge besides what I have read to try to understand the issue. 

The problem is that at the moment I try to run the server, it gave me a list of errors and I couldn't figure out what's the issue.

Here you have my [application.yml](https://pastecode.io/s/585ugnjh) for reference

I downloaded the plugin lavasrc-plugin-4.3.0 and put it on the \plugin folder and the lavalink for the application.yml is the version 4.0.8

Here is the log I could gather
[log.txt](https://github.com/user-attachments/files/17373704/log.txt)

I appreciate any comment or information to resolve this issue!

**Comment by topi314** [comment]
> Caused by: java.lang.IllegalStateException: Youtube LavaSearch requires the new Youtube Source plugin to be enabled.

this means if you enable the lavasrc youtube (which does not support playback) you also need to enable https://github.com/lavalink-devs/youtube-source/
