### ISSUE TITLE
Getting "No token provided" from spotify lyrics source

### ISSUE THREAD

**Issue by clearlakes** [topi314/LavaSrc#238]
When fetching lyrics via Spotify, this message has started appearing:
```
[Lavalink] [  XNIO-1 task-2] c.github.topi314.lavasrc.LavaSrcTools    : Server responded with not found to 'https://spclient.wg.spotify.com/color-lyrics/v2/track/37a3nbkyvkqK5KiDNNgvqA?format=json&vocalRemoval=false': 
```
Using that url with curl:
```sh
$ curl -s "https://spclient.wg.spotify.com/color-lyrics/v2/track/37a3nbkyvkqK5KiDNNgvqA?format=json&vocalRemoval=false"

No token provided
```
It's 3 in the morning right now so I thought I'm probably doing something wrong but this use to work before without any changes to the config and the Youtube lyrics source works and the Spotify audio source also works (and `sp_dc` is given for lyrics), so I'm not really sure what could be causing this other than a change in Spotify's API maybe? Either way thanks for maintaining this!

**Comment by DRSchlaubi** [comment]
I can do that for you

**Comment by DRSchlaubi** [comment]
You're getting "No token provided" since your curl command does not specify one, lavalink get's 404, which is likely because your [track](https://open.spotify.com/track/37a3nbkyvkqK5KiDNNgvqA) does not seem to have lyrics, maybe it has them in a different region, but it does not have them for mine

**Comment by clearlakes** [comment]
I see, my project was catching all statuses and treating them as JSON, and I guess I've never reached this case so the 404 not returning that was unexpected. Thank you for clarifying
