### ISSUE TITLE
Spotify deprecating some api andpoints

### ISSUE THREAD

**Issue by Vexify4103** [topi314/LavaSrc#241]
Some Spotify supported URLs and queries are no longer working because Spotify deprecated some endpoints of their api such as https://developer.spotify.com/documentation/web-api/reference/get-recommendations

Read here: https://techcrunch.com/2024/11/27/spotify-cuts-developer-access-to-several-of-its-recommendation-features/#:~:text=Spotify%20will%20no%20longer%20allow%20developers%20building%20third-party,announced%20in%20a%20developer%20blog%20post%20on%20Wednesday

**Comment by DRSchlaubi** [comment]
Well I was already wondering why these were public documented endpoints in the first place, maybe we can use some internal APIs similar to how the lyrics implementation works

**Comment by topi314** [comment]
If your app is extended quota mode there is nothing you need to worry about. Therefore no change is needed in LavaSrc.

**Comment by topi314** [comment]
You can leave the client id & secret empty to use anonymous spotify tokens, which apparently still work

**Comment by topi314** [comment]
seems like anonymous tokens also can't use the recommendation endpoint anymore

**Comment by topi314** [comment]
seems like anonymous tokens also can't use the search endpoint anymore

**Comment by topi314** [comment]
https://github.com/topi314/LavaSrc/pull/273

**Comment by topi314** [comment]
> seems like anonymous tokens also can't use the recommendation endpoint anymore

seems like they can again lol
