### ISSUE TITLE
Feature Request: Use accessToken Instead of clientId and clientSecret for Fetching Track Information from Spotify

### ISSUE THREAD

**Issue by dazzypark** [topi314/LavaSrc#245]
Could you modify the LavaSrc to use accessToken instead of clientId and clientSecret when playing music from Spotify?

Reference: https://github.com/Nansess/BaldMan-LavaSrc/blob/master/main/src/main/java/com/github/topi314/lavasrc/spotify/SpotifySourceManager.java#L238

> When using Spotify with this Fork, note that while the usual Spotify API enforces rate limits based on the application's client secret and ID, this fork uses anonymous tokens instead. This means you won't encounter rate limits due to client credentials, but keep in mind that you might still be rate limited by IP (429) if too many requests are sent. However, this method significantly increases the ability to accept Spotify links compared to using your client ID.
> (In readme)

**Comment by topi314** [comment]
This already works, just leave them empty.

**Comment by dazzypark** [comment]
Oh my goat, topi

**Comment by 1q3** [comment]
i'm trying to do this in Lavaplayer but it still throws "Spotify client id must be set" which was removed in https://github.com/topi314/LavaSrc/commit/cbc40b9720e1c90702fc8cfb1d8182e8a65af6e9. am i doing something wrong or is something up with the builds at maven.topi.wtf?

**Comment by topi314** [comment]
which version are you using?

**Comment by 1q3** [comment]
i tried 4.3.0 as well as the latest snapshot

**Comment by topi314** [comment]
it was added in `4.2.0` are you sure you are using `4.3.0`?
sometimes you need to clear caches and such. Feel free to provide screenshots etc
