### ISSUE TITLE
Spotify Regex broken, links work, search strings don't

### ISSUE THREAD

**Issue by Moquent** [topi314/LavaSrc#77]
![image](https://github.com/topi314/LavaSrc/assets/63721912/f181caa6-6bbb-45e6-a803-0c08fff9a13f)

**Comment by topi314** [comment]
nothing is broken, it just can't find anything for `whaledontlseep sleeping town`

**Comment by Moquent** [comment]
![image](https://github.com/topi314/LavaSrc/assets/63721912/985197ed-3234-4ce6-87b1-1606637b8f13)

**Comment by Nico-ITA** [comment]
https://community.spotify.com/t5/Spotify-for-Developers/Spotify-Search-API-Issue-404-not-found/m-p/5595024 Spotify API issue .
