### ISSUE TITLE
4.0.0-beta.1 Build failed

### ISSUE THREAD

**Issue by Tomato6966** [topi314/LavaSrc#81]
![image](https://github.com/topi314/LavaSrc/assets/68145571/33bc1991-146e-41dc-a62c-d9b777a02c4e)
can't download it from jitpack
![image](https://github.com/topi314/LavaSrc/assets/68145571/49300ff4-26c8-41d2-919e-03df2e0af869)

**Comment by topi314** [comment]
As described in the readme you should not use jitpack but `https://maven.topi.wtf/releases`
