### ISSUE TITLE
Auto complete support

### ISSUE THREAD

**Issue by DRSchlaubi** [topi314/LavaSrc#88]
Many sources provide search suggestions, so it could be useful to have something to access that like a source manager

Related:
- https://developers.deezer.com/api/search/autocomplete
- https://github.com/DRSchlaubi/mikbot/tree/main/music/player/src/main/kotlin/dev/schlaubi/mikmusic/innerttube
- https://developer.apple.com/documentation/applemusicapi/get_catalog_search_suggestions

**Comment by topi314** [comment]
released in https://github.com/topi314/LavaSrc/releases/tag/4.0.0-beta.4
