### ISSUE TITLE
Maven resource not found

### ISSUE THREAD

**Issue by LewdHuTao** [topi314/LavaSrc#92]
Is it a known issue, or is it only on my side that I can't download the plugins jar?

here the maven url: https://maven.topi.wtf/releases/com/github/topi314/lavasrc/lavasrc-plugin/3.2.5/lavasrc-plugin-3.2.5.jar

![image](https://github.com/topi314/LavaSrc/assets/90232327/94c2b27d-2b64-43ac-a6ce-ed36f0212cac)

**Comment by LewdHuTao** [comment]
Versioning classification:
Lavalink.jar v3.7.7
LavaSrc.jar v3.2.5

here the error that come from lavalink log:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$bccd5d7c]: Constructor threw exception; nested exception is java.io.FileNotFoundException: https://maven.topi.wtf/releases/com/github/topi314/lavasrc/lavasrc-plugin/3.2.5/lavasrc-plugin-3.2.5.jar
```

**Comment by topi314** [comment]
for lavasrc v3 instructions see https://github.com/topi314/LavaSrc/tree/v3-legacy
